# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database/account.sql:/docker-entrypoint-initdb.d/account.sql
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
